[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "468da6e3a20bfca46eec90bb3e403a113257f2e9"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "6a4253f93509378a00076dadbe35903cb7e272a8699cd3f62a46c059dded2423"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f4387e7be749e8229c554a109bd06238bcecdb6"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "ed2f23538b80653697726d2bcf4cb6902b22df341f569104f2295eeda3241350"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b2aafdf1285a250ebed8d457ace90fa5886e720"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "c317783ce69d110a801caab2deaecdb9b9e1ca347d683494f411091c5114a4a2"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a1ea3c8a1154c06e447a4ac9be24a4fa95d2960"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "c6b1b24ad156ba0f7e11d0146cbeb347d83161621e3d7eb15111b1eac528c075"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "2f84eb92c9985ee65369526ac62cf8d6d037d6c7"
os = "macos"

    [[RDKit.download]]
    sha256 = "04a1a00ebc02e606dbafcf9e48b2041db0808d617bb511e3df436b1dfdba3b39"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05cc9201e36709e2c80657d6cd6036a4e19746bc"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "23d91c197271cef16a90a2ca6e56c976997475b81724c30189391eac5bff4458"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf864a640c2c3f16f9bed97bb67e17967c95f251"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "e8941fc2ea06dbadbae645d706011b3b8f26b250d6d2740200e9a364d35e89ad"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+2/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx11.tar.gz"
