[[RDKit]]
arch = "aarch64"
git-tree-sha1 = "5aa25daa9d4dd0d6e9c71b1e7293399e8c2d016a"
os = "macos"

    [[RDKit.download]]
    sha256 = "63f0b97e1eabdc5636b8c2454beb06e1d6b5e06c3cb6e3328397f4c92572082f"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.aarch64-apple-darwin.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78e4a233d7a216abddaff95eb24900d8401419fd"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "d4abb6f311710916a10c45b9254d32667159c2a443728a06def4ca86262fa212"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0907f68794ef2b1aad4f90d716898ac16e6be9ba"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "859d96cf1c4134529eccdeaee2d31511655bebee55a142609645bd41653db72c"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91252d91eda9e16a33b532824b5f16190d9cbcba"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "44c6421527b4a28ba305a819e3dd7f56777dfc23d5a6d38adb94675e33236319"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8746996d15c3ca36e151fabe99efbc86e6461e1d"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "682bc97f6e2a98fe50d6db937ff2cf7aa5fe20c3d66753c5fa61cb47d0a75cec"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "6687cba0fc3e73463fec626760b6a0dc37e89777"
os = "macos"

    [[RDKit.download]]
    sha256 = "9f5ec2fe678196803b5eb990652b2fd8bc3da1802cfeba9df7349eedae0a59e5"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61b1ff28d3e75de55415dcf3341471bd90802bea"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "675d1553059423e165c180a6825c734fee932b3d6dab9f5f6eecb2279e12cf7c"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3921da617a6dfaead03ef2092bde61f9ebcf9c34"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "7b6861b82fd53dd882d324dc05a4de0f33c1726154dc9d9af84b416af147b9d8"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b72ebd4fc18ce97329cdf233e8807ff1fe62297"
os = "windows"

    [[RDKit.download]]
    sha256 = "50d1ef5a7a1d9b98e3c508b21d232329ca282b9485a06474ed12751a43eb0f55"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c25c64dd5744927f8285d4172c73c0ef9e658d2"
os = "windows"

    [[RDKit.download]]
    sha256 = "fe2501b0b627c1b86a1c5ec85b5924f0770def675e6930624295867c2d8994aa"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.1+0/RDKit.v2022.9.1.x86_64-w64-mingw32-cxx11.tar.gz"
