[[RDKit]]
arch = "aarch64"
git-tree-sha1 = "8cdc7e4b909b10dab351fd4d465cb42ef3e95188"
os = "macos"

    [[RDKit.download]]
    sha256 = "201f08139d1248f6b6fcd2ce49dff017cd161366b9a17a6ff798d6718027bde9"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.aarch64-apple-darwin.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11f6761b3e61de59e9a79eb66df646dac9d60493"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "07b18e86224fa0e32745409ffbf6e9e13b6d3afc9aefa89a7de1955a88b58968"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cd83fce4fb5406bb85ce952b7b6b41119d08025"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "c871aabf877f4e6a9c98fe8ba13f7edcceecda78873531a7eee2ad16bba10a4a"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a88141ac7f36a441b2dcbbf5f99221bd8e90ae4b"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "0d10389dd413b9bcf8127eff36a31ad119e582091442e4815a5e0d7bb30e1a76"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60fa279daa0a9d2eebd4bba4bd77ac348458f90e"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "18b4edd041453c4c8d3b2003d0cd480c6cf00e2aa456cbce0b70613cf71ef147"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "a5c08497c5e6ad87af59ae15acfeb9cefdd06030"
os = "macos"

    [[RDKit.download]]
    sha256 = "f3627160db1dc3b2a8967002a725fffbe3ca95f2ee61e9645f96af552b4eb988"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad49f90c41f73bf90de9dd02d2620bc2393c1cfc"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "94b4744e0ca86a49ba9d79af6bc1aec34dab6c2f90f5125f03bde0d8cb079f33"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff255b2a85a0a5fa92d931726aa1e93ab7f68294"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "ad773ce0bb8e17a8c0bda743022dcc598d21080d66a20712fd84f49c8063a796"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.x86_64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ff11fc96bca4e7b5042653238ac27d3d7a3b11a"
os = "windows"

    [[RDKit.download]]
    sha256 = "677c95726ea1ba24b12e795707d2a60c990105b6c0b25cf2487b358072b4df3c"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ee0f80f26a6cf04b746bfa7fa400ef083506afb"
os = "windows"

    [[RDKit.download]]
    sha256 = "06d73f53dd92dd4947284c83d68590519aea7c56567e552f0db8ed9b750d1559"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.4+0/RDKit.v2022.9.4.x86_64-w64-mingw32-cxx11.tar.gz"
