[[RDKit]]
arch = "aarch64"
git-tree-sha1 = "8524da4a458e34ccc35b4d92167d2fc5fc63315d"
os = "macos"

    [[RDKit.download]]
    sha256 = "75bbb78764413df89a215966729a9bc236ce15095724fe8946cf61213afecf71"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.aarch64-apple-darwin.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf160767c7b7422fc485206b09d86d905e19ff54"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "b91323c30fc8be62db81e4fa37271659486e6f0a10f66930eae0a7d883cdb4ea"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39009229fe96568a8e97aa40ff9eab40469a3991"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "93f687bb8c481a8fe621a5c751c1d66ec4d3904bafb4d416343e4713a22d3d77"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "972381cbf755bbc3777b285fc545fadc6dfe6e7c"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "7466bc67e7b7ed2866e51b1b1da52d81fafe54e3b4dde18dc9944053d3398e6a"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3e913e8567c6cc4ac3814ab146c6225fc07d242"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "90cb395008a7b413bee202d4fcfc3bba5666e938baece70bedd4ce1f997e0655"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "72f2c0ec05f2c0dc71fa777c3906f91dbc878783"
os = "macos"

    [[RDKit.download]]
    sha256 = "7e4270dca55ef918f8ada6f3d34ae842943208d7463026e105948f9cd7cd25f0"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64d8df8f3dffef4fa3b63980873266edf69ab962"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "034f5d2f74195354c0a2e9932f7bc3eee2634eb4974abc3d7e2f1bc3313b3c17"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "349122f4a22ed97a993052624ebba39f916c7e90"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "6382d7a85a16dd07a63b18b11555efacb31f1f7e86214a697cb03707520c4957"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d53a952b158966971e9643f8f68aaf36a59715a"
os = "windows"

    [[RDKit.download]]
    sha256 = "ca12511540af23ada18c9ad8b05f931eddeab6d85d5458bcbe2467e3a108c02b"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66eb04ab70aa935fa7a3ae1bdd7c874d4e30dee0"
os = "windows"

    [[RDKit.download]]
    sha256 = "6649657f8a0efeed37e55b9dd5b64bc36e40e0d32e388e2e787664924d43a9b4"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.3.1+0/RDKit.v2022.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
