[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68bda3d004d1ae73bf9f5905db5fafeb130b3ddc"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "788a83503570745798b1b2bfdb3a22a85b3fe84ad4ef4d4a8305e49e7e4d21f9"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a484b6e311fe5cc890c03902baf9dc29d8b8ca84"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "246cf9e2301d0baa1cae2dc48501c8340eb34a98c9d39ce597435594e955013d"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c0bf797bc12966ef7d77e0749f8715f2e6a7c2e"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "c3228c2b62869a5be0fbea69e1f5da2d65f31ff3e8bc72511383196f46f09655"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc96c38df4bf571767770a56c8cf210b5a6a5545"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "93ada52c9f1c82152be958ac27577c7129da020f13dd20057c812ba514c63f65"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "5f74e2a01383410ce3bf5039e69a8d8778c048f5"
os = "macos"

    [[RDKit.download]]
    sha256 = "3d45187c54b3b5f59dde098aba0f745c6548b48a918a345ed37d3afd3e1116ef"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2630020225fe40afc84ed8fe5e5d8b8a592b1a6b"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "827feb1a558de600b7b7a3ddaba49d91a0a1c6478ea5067d66972f7fdb44a3ce"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdc0db6ea9074b46796dbafeecb9ba6b75056566"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "37dffca210918360610da87af2c4dcb9ef29a32a8dd8b1f4c7fce478223f6998"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+0/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx11.tar.gz"
