[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "654e2878c4b9b4a15f577f72110e86871968574e"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "335c71f7354152f36276e3e9ea3955ec43da20888fed393622272fd6e1f02588"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23f4fe91dfc5718d5ac41263e6282f4032663f5f"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "475b54ccb8705bb44a67ef657c840d197b471b68e89834891780d0b9f11d986f"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9f8f4e369733f056ebb07661b0e4caaaf7d4cec"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "d8bbcd66d142de7da2298bf76795e20ac1accaf92bc3dba59514bd2c981d3524"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4a6a590d09707fe61f558fda2d0f825124acf07"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "9db2170ed065c13b683c5c3f1dfdcaf2e555eb79d56b488a8951f4e18eb5f175"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "e8cac397b3c4ff1ba08394e3e8d56c73d97dca75"
os = "macos"

    [[RDKit.download]]
    sha256 = "a050a6d92a19ffd49f7b09c93b26d59f877c1adcad66048526bed4d57a90998d"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e47e9680ee0d0781dca8b7006da1a8e92bfa07f"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "ceaa6de0b761b614b05a9b5ae4d19593596707af6bc2ce7ea7374b534ebcc3a4"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bae3215c7ac5354e9d1b549bdbdf7c82b2701f04"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "6a5914d75caca2f95ee1831d0bdd07d4935966b7b0e11ed00045d18d18db3f80"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.1-pre+3/RDKit.v2021.9.1-pre.x86_64-linux-gnu-cxx11.tar.gz"
