[[RDKit]]
arch = "aarch64"
git-tree-sha1 = "e8d449acee3ab7b06590da60d6c820ab493679d6"
os = "macos"

    [[RDKit.download]]
    sha256 = "f62dbd900d24dd77cf1570579225488759a971e59352a4519e0e7dd53ea73e27"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.aarch64-apple-darwin.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d2efa6faf01680411b59564b5be6489c1af8457"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "6a1a8a1e34f76ecd8e80d17a9f253cf43222f00b2ac9fb0747de9f6a1551cf0c"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99b8b3a864e48207799d7fb45ad647fd3929c3f8"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "7f73a34dc16e1d63c023f9228f7c9c6b2b7322f76edb1e7bdc96343342c4dafc"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fbb9bf40f03a433da748d96ffcebb958a55e754"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "0644729f69f66061bba021cbc73d4a51b69366b677daf7602b57915232d12035"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64ad5067feaa038659ad3ea5f752f9b1beb651be"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "f23ff410f8f6961a0691c63c5b74ae0757dfadd8204fbc542d78167310ff9d7d"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "99b15318ef7409c051c0a2eedb5be81ec74dbd04"
os = "macos"

    [[RDKit.download]]
    sha256 = "c942f3911c2c8a75556f40e522c9aa09f0cfc1bc6a55c1d50741a2daedabdd44"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20e19c708c710710221bb3a9a11e6efcd79d60f7"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "b59fa6647464f202ece353efc2755267778d2f0f77bda8ab00fe32854474937a"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2fbe2d67f6dd770be63425f7ffc9047b3dfcfc5"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "c198d9a94d8a16199464c16e5a056bdf383e35a24910b54e56036082de7e0376"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2021.9.2+0/RDKit.v2021.9.2.x86_64-linux-gnu-cxx11.tar.gz"
