[[RDKit]]
arch = "aarch64"
git-tree-sha1 = "2c13f166e74a9c16140639052ba0b48a0492ea44"
os = "macos"

    [[RDKit.download]]
    sha256 = "426d05bc58768de4ebe9d64eb746f429b8ceb2aff9e748d3c7f553309249d812"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.aarch64-apple-darwin.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a359b6f1f90864f331314813d5b94fac22fed078"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "9aad7ad01ce13b9f1e47846a3bd7ef530420e09c44e4c7f0c04a0d4ff7279cbc"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.aarch64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "587772f064382ab1356c2ab3c6c65fd7e751d885"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "9d25875d23a745154a4506ed61bcff892111a84aca4f69499edcbd6fea993444"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.aarch64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13292f9ebd438b77a10bc161788d68596e329517"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "6288d1dfc07357fb5659af02dd4643de6767528b17f8b97f6f88e2a0a763d61b"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.i686-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb1aab6b207ca62f5de0704e9208782e00a22062"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "0b8461ff03d7cd30326750d7e7534851143048ba4085548c09cccc977c59bece"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.i686-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
git-tree-sha1 = "b1c650d0a1074767051e96e6f8610b941c7bc2aa"
os = "macos"

    [[RDKit.download]]
    sha256 = "8f40a6f282baff2363e76f32ce94a3bdca948ffa37fc779cb2c6cec8695c1a17"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.x86_64-apple-darwin.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bd45d39e9ea7fdbfe6e165a68277431706644d3"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "e775e24d66696515d7faa3b34a33bf9861097e52a70b7249a3cfbc4f74460a72"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.x86_64-linux-gnu-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "693cfb86ee408cee69874b767d5a308d796d46ed"
libc = "glibc"
os = "linux"

    [[RDKit.download]]
    sha256 = "1acd273635c8557376cea0faf1ae640dd5b79ac58baaef2df3855bb7f5ae36a8"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.x86_64-linux-gnu-cxx11.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6aaa0f2f45d75cc2f1bebdf63a0436ccf976c87"
os = "windows"

    [[RDKit.download]]
    sha256 = "2876b606daccf38b09c4f50848d948c95b194191fa18ec7afaade09e20b47029"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[RDKit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4d1680da219f8ee3603dda21a253cc6133491a1"
os = "windows"

    [[RDKit.download]]
    sha256 = "b700b599ba89cf397e072d7f46c95e0926e85421d4633dfec09c0b3d4227124b"
    url = "https://github.com/JuliaBinaryWrappers/RDKit_jll.jl/releases/download/RDKit-v2022.9.5+0/RDKit.v2022.9.5.x86_64-w64-mingw32-cxx11.tar.gz"
