# Autogenerated wrapper script for RDKit_jll for x86_64-apple-darwin
export librdkitcffi

using FreeType2_jll
using boost_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("RDKit")
JLLWrappers.@declare_library_product(librdkitcffi, "@rpath/librdkitcffi.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll, boost_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        librdkitcffi,
        "lib/librdkitcffi.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
